print("Fourth Project")
print("Nathan Vasconcellos Vicente")
print("ASCII ART")
print(r"          __     __  ")
print(r"         /  \---/  \ ")
print(r"   ,----(     ..    ) ")
print(r"  /      \__     __/")
print(r" /|         (\  |(")
print(r"^ \   /___\  /\ |")
print(r"   |__|   |__| -")